version: '3.7'
services:
  xnat-web:
    # image: fcbg/xnat-unige:1.8.8.24
    build:
      context: ./xnat
      args:
        XNAT_VERSION: ${XNAT_VERSION}
        XNAT_SMTP_ENABLED: ${XNAT_SMTP_ENABLED}
        XNAT_SMTP_HOSTNAME: ${XNAT_SMTP_HOSTNAME}
        XNAT_SMTP_PORT: ${XNAT_SMTP_PORT}
        XNAT_SMTP_AUTH: ${XNAT_SMTP_AUTH}
        XNAT_SMTP_USERNAME: ${XNAT_SMTP_USERNAME}
        XNAT_SMTP_PASSWORD: ${XNAT_SMTP_PASSWORD}
        XNAT_DATASOURCE_DRIVER: ${XNAT_DATASOURCE_DRIVER}
        XNAT_DATASOURCE_URL: ${XNAT_DATASOURCE_URL}
        XNAT_DATASOURCE_USERNAME: ${XNAT_DATASOURCE_USERNAME}
        XNAT_DATASOURCE_PASSWORD: ${XNAT_DATASOURCE_PASSWORD}
        TOMCAT_XNAT_FOLDER: ${TOMCAT_XNAT_FOLDER}
        XNAT_ROOT: ${XNAT_ROOT}
        XNAT_HOME: ${XNAT_HOME}
        XNAT_EMAIL: ${XNAT_EMAIL}
    ports:
      - 8080:8080
    volumes:
      # - ./xnat/plugins:${XNAT_HOME}/plugins
      # - ./xnat-data/home/logs:${XNAT_HOME}/logs
      # - ./xnat-data/archive:${XNAT_ROOT}/archive
      # - ./xnat-data/build:${XNAT_ROOT}/build
      # - ./xnat-data/cache:${XNAT_ROOT}/cache
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - xnat-db
    environment:
      - CATALINA_OPTS=-Xms${XNAT_MIN_HEAP} -Xmx${XNAT_MAX_HEAP} -Dxnat.home=${XNAT_HOME}
      - XNAT_HOME=${XNAT_HOME}
      - XNAT_DATASOURCE_USERNAME=${XNAT_DATASOURCE_USERNAME}
      - XNAT_DATASOURCE_PASSWORD=${XNAT_DATASOURCE_PASSWORD}
      - XNAT_DATASOURCE_HOST=${XNAT_DATASOURCE_HOST}
      - XNAT_DATASOURCE_NAME=${XNAT_DATASOURCE_NAME}
    healthcheck:
        test: ["CMD", "curl", "-fL", "http://localhost:8080"]
        interval: 30s
        timeout: 10s
        retries: 5

  xnat-db:
    image: postgres:${PG_VERSION}
    expose:
      - "5432"
    volumes:
      # - ./postgres-data:/var/lib/postgresql/data
      # 
      - ./postgres:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=${XNAT_DATASOURCE_ADMIN_PASSWORD}
      - POSTGRES_DB=${XNAT_DATASOURCE_NAME}
      # variables for the sql script
      - XNAT_DATASOURCE_USERNAME=${XNAT_DATASOURCE_USERNAME}
      - XNAT_DATASOURCE_PASSWORD=${XNAT_DATASOURCE_PASSWORD}

  robot-framework:
    build:
      context: rf-build
    # user: "${UID}:${GID}"
    volumes:
      - ./reports:/opt/robotframework/reports:Z
      - ./tests:/opt/robotframework/tests:Z
    environment:
      - HOMEPAGE=http://xnat-web:8080
    depends_on:
      xnat-web:
        condition: service_healthy

